title: Intelligences
description: >-
  <!doctype html><html lang="es-419"><head> <script
  nonce="qoTzacGjaRM2Hv28/0imjQ==">(function(){window.google={kEI:'p4mtYdGtGIOBqtsPmPq8uAE',kEXPI:'0,1302536,56873,6058,207,4804,2316,383,246,5,1354,4013,1237,1122516,1527267,51224,16114,28684,17572,4859,996
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
